### ISSUE TITLE
Error: libsecp256k1.so.0 missing and TonLib attribute issue in pytonlib

### ISSUE THREAD

**Issue by enavid** [toncenter/pytonlib#65]
Hello,

I'm using pytonlib in my Django project running on Ubuntu. I’ve encountered the following issue during runtime:

‍‍‍```
{'msg': 'libsecp256k1.so.0: cannot open shared object file: No such file or directory', 'method': 'deposit'}
Exception in tonlibjson.__del__: Traceback (most recent call last):
  File "/path/to/venv/lib/python3.12/site-packages/pytonlib/tonlibjson.py", line 133, in __del__
    self._tonlib_json_client_destroy(self._client)
AttributeError: 'TonLib' object has no attribute '_tonlib_json_client_destroy'

Exception ignored in: <function TonLib.__del__ at 0x72e2b810da80>
Traceback (most recent call last):
  File "/path/to/venv/lib/python3.12/site-packages/pytonlib/tonlibjson.py", line 136, in __del__
    raise RuntimeError(f'Error in tonlibjson.__del__: {ee}')
RuntimeError: Error in tonlibjson.__del__: 'TonLib' object has no attribute '_tonlib_json_client_destroy'
```

**Steps I’ve taken:**
  1- Installed libsecp256k1-dev via sudo apt-get install libsecp256k1-dev.
  2- Verified that libsecp256k1.so.0 is installed correctly using ldconfig -p | grep libsecp256k1.
**My setup:**
  1-Ubuntu 
  2- Django 5
  3- Python 3.12

I ask this question in stackoverflow(https://stackoverflow.com/questions/78981384/error-libsecp256k1-so-0-cannot-open-shared-object-file-with-pytonlib-on-ubun)

It looks like the issue might be related to the TonLib class, specifically the missing _tonlib_json_client_destroy attribute.

Could you provide any guidance on how to fix this or if there’s a missing step in the setup?

Thanks in advance!

**Comment by pouya817** [comment]
Problem with Code Deployment on Ubuntu Server

I am encountering an issue when deploying my code to an Ubuntu server.

The code runs without any problems on Windows, but when I attempt to deploy it on an Ubuntu server, I receive the following error:


Any guidance or suggestions on how to resolve this would be appreciated. Thank you!
